add_newline = false
command_timeout = 2000
format = "$all$directory$git_branch${custom.git_status_dirty}$git_status$cmd_duration$status$character"
right_format = ""

[character]
error_symbol = "[❱](red)"
success_symbol = "[❱](purple)"
vicmd_symbol = "[❰](cyan)"

[cmd_duration]
format = "[$duration]($style) "

[custom.git_status_dirty]
format = "[$symbol]($style)"
shell = ["zsh", "--no-rcs", "--no-globalrcs"]
style = "white"
symbol = "•"
when = "test -n \"$(git status --porcelain 2>/dev/null)\""

[directory]
fish_style_pwd_dir_length = 1
style = "blue"
truncation_length = 1
truncation_symbol = ""

[git_branch]
format = "[$branch]($style)"
style = "bold green"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = "[($ahead_behind$stashed)]($style) "
stashed = "≡"
style = "cyan"

[line_break]
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'
style = "white"

[status]
disabled = false
format = "[$symbol$int]($style)"
pipestatus = true
pipestatus_format = '\[$pipestatus\]($style)'
symbol = "✘"
